language: rust
rust:
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
deploy:
  provider: heroku
  api_key:
    secure: LfhTyvOr40DS/LzIbSTaekpNBeCxsLgFzWTpOHGUILjkhhUDejX+ctaP/hU/07D+FI/VIlh9yuWcZn/0g7CkdIBz03k4LltHjPtSqNpM1TT/GxODK2gLIeFWLvw8aB11rk/UQNqyrlhuNFNTcVEO4002Z+CTAOpv2jcIK/yL0j/Qml5m4Mx0dTSmu/6lqcrSHgJ0ZqRNqPToVb7bkI6/zoCL/IMaRKVQMx4y11gC0O9XzZcFmMtLG//Q8RC1GGgUalVejkkqv/o4uKMzVdWIMnmaMjt2puDtrY+j4d3t+Csp/qJsvvA56yiebaNFj3RMPaPaio0HnOB8eDIxXlt7SUhxdcfNgaKRq2TjpTSO4JtSAvL0KKqi1kb4ldcDpNU5Lf3LnQ6LPg41QY9zDqqDNpPTeKvyCN9o1Wth3PZ6cdX3JaPQhfDPN6p3uUn3hHZOeK21K8kqGZIkh30esgrzrBLV2+jJ2djuNyPn+1hGB321NsJfVH11nYzBmF3AMSzWeLKNzf8zAqUaBLclyb/dIMnNYihyjQdHMedDJT9Px8mxSorHHJ40i8nEitpGsxtMxbp4o79nQPaBxehiyAMKRUnic7I9oiK7q36sZvr+tz4ddkYhXS7SLthiEOjL8fNdLYAv2VSjz4o24205j+hS2Z1jKc9VpDAiwDIixBl1NG0=
  app: hello-rocket-app
  run:
  - cargo run
