language: rust
rust:
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
deploy:
  provider: heroku
  api_key:
    secure: wRv938RSY9JYhBhUPXeCgb0QAFGPJbQaxvuNitYiyRhAIW7mzQu9VAfjDHj2VsdN0bdf6ZEBG8BrBSMrIpDeebeC4o9eJGP85aM0hF7CIRqjJuzFizHC45v+okonPCe7mQkzs5sEIlpRrED2XN6qvd4YeONBzjGbKnUcHuKWak8TF18y0QhNHoPBEYtbffHg1jvnkNmfr4jo8xZK0o2WuS7Ou0bEPJOEol3o+MO3StTmpwh+ZVvhIwYWA2Wy4ZgIzDxUYt+6F/o7RHHOA8vy4sCwX0gys7boNc8IcrfWRpeD2EElMgVa+L7cAijf35wq/Ymy4XSBq833Hpi9yNgKBHPt+f/di8ZvSH/e1VE6b97hgRD70qfIZJc4EM2zpXe+yG5C5zt7JOBlPzLjJPJ0JIBtDFKAbwIIbG2Dgt/1QS9mus5JDC1U7SPwvEsnHVk+/GHCrxBmwehR1/2OT3fiqaX8iE212eAGv8CaQ2gHdYbXxTr8+V6w+vcN1lBzMv7YYXm/m63Fed3Tt7YhILbimrNmB8wVqxUi54/H5pXhnrzl9Ly+veSlKJESMQgcy7jZYm2B4K6xqmW5i/qWDkFmIL1HZlSLN4rbbmY/jXTwRlbZ95Xl6/sjI9+0mVmcZ1cVN11t0dV/xLDg5o9WeT+PKiMUZehkqVhvZICs8GUp4Bs=
  app: hello-rocket-app
  run:
  - cargo run
